server:
  port: 8080
spring:
  datasource:
    url:  jdbc:mysql://localhost/studentdemo?characterEncoding=UTF8&useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


    ## 误提交了文件
