server:
  port: 8080
spring:
  datasource:
    url:  jdbc:mysql://106.54.228.53:3306/studentdemo?characterEncoding=UTF8&useSSL=false
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
